{% set version = "0.10-63" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tseries
  version: "{{ version|replace('-', '_') }}"

source:
  url:
    - {{ cran_mirror }}/src/contrib/tseries_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tseries/tseries_{{ version }}.tar.gz
  sha256: b99eba075d8dedef20cffb89a185be247f8f87ffeb65af96e2487d36a6f5cae2

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-quadprog                 # [build_platform != target_platform]
    - r-zoo                      # [build_platform != target_platform]
    - r-quantmod                 # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-quadprog
    - r-quantmod >=0.4_9
    - r-zoo
    - libblas
  run:
    - r-base
    - r-quadprog
    - r-quantmod >=0.4_9
    - r-zoo

test:
  commands:
    - $R -e "library('tseries')"           # [not win]
    - "\"%R%\" -e \"library('tseries')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=tseries
  license: GPL-2.0-or-later
  summary: Time series analysis and computational finance.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
