{% set version = "0.10-58" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tseries
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tseries_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tseries/tseries_{{ version }}.tar.gz
  sha256: 0edee71941bb8ea3d5ecad6b6a84d8019081f862138433b3c5e6fa5a4cbca724

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-quadprog                 # [build_platform != target_platform]
    - r-zoo                      # [build_platform != target_platform]
    - r-quantmod                 # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-quadprog
    - r-quantmod >=0.4_9
    - r-zoo
    - libblas
  run:
    - r-base
    - r-quadprog
    - r-quantmod >=0.4_9
    - r-zoo

test:
  commands:
    - $R -e "library('tseries')"           # [not win]
    - "\"%R%\" -e \"library('tseries')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=tseries
  license: GPL-2.0-only
  summary: Time series analysis and computational finance.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: tseries
# Version: 0.10-47
# Title: Time Series Analysis and Computational Finance
# Authors@R: c(person("Adrian", "Trapletti", role = "aut", email = "adrian@trapletti.org"), person("Kurt", "Hornik", role = c("aut", "cre"), email = "Kurt.Hornik@R-project.org"), person("Blake", "LeBaron", role = "ctb", comment = "BDS test code"))
# Description: Time series analysis and computational finance.
# Depends: R (>= 2.10.0)
# Imports: graphics, stats, utils, quadprog, zoo, quantmod (>= 0.4-9)
# License: GPL-2
# NeedsCompilation: yes
# Packaged: 2019-06-05 09:12:18 UTC; hornik
# Author: Adrian Trapletti [aut], Kurt Hornik [aut, cre], Blake LeBaron [ctb] (BDS test code)
# Maintainer: Kurt Hornik <Kurt.Hornik@R-project.org>
# Repository: CRAN
# Date/Publication: 2019-06-05 09:15:16 UTC
