appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: dNE1xB2rFemYTtHxJwVpnRFBI+MtBr5d7BgOQZWbqiEvKFth3SFO/E0nQF6CLkIsNA9tTI1Ya0qxMeJ8iZLWlPRYkPPEkIoiKmhjAsOtsUtquMidqUmPukFQdLs8v+DWwikOhQcGDSH/xhapYlq8o1x15LJZAsPkjZk6Cp4s9Dewu/CoaXjlpEg0HxeTlf47thR9GHqphSy+sL02hDXYob66ycRBspKnVZqlA2cHggCKnQoBI720nq5cOUW5iNiqWtu6ZOgV1Iq7gXDZrpJmgKSLd7jY11XN5+A1ZHSvGpCm2YHbAP+KtyQYpH8nFSqwZVBCHWiqfg70NHIs9L9rqEafBiU64jkbX7igxvgZKLpb92Xw+yEkgoAcc2RF/jdRwqCb3DDQVKZ4DKzGhgB38YlR8pfyQMtvl0iz0QP6skJIFjNdls/bsD2dQjwX9g1l4Fhw/XhG2kv2NsNipUJ6n2pyXJ/KJT14ImTpWkB3ENBLrtsc1pgWBUH66P8sqe+ddLtk2A/NtRHHYAH60z+YRJPaH0KoBXQq67pbPv5C66IEWBnpMu+XaavqtxgY/k7BMe2VJ47m5jHhR1hwtVQr8UEKPuExn7QnhvLwjl4eHU415eebUngJEIL7PyHPEv1bygB16r7ajrLcoIvOFwxVCj057igG5ZT/x31KWm5rA8Y=}
